---
apiVersion: skaffold/v2beta23
kind: Config
build:
  artifacts:
    - image: soju
      context: ./..
      docker:
        dockerfile: Dockerfile
        buildArgs:
          VERSION: "{{.VERSION}}"
    - image: tiny
      context: .
      docker:
        dockerfile: tiny.Dockerfile
deploy:
  kubectl:
    manifests:
      - "kube/*"
