---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: soju
  labels:
    app.kubernetes.io/name: soju
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: soju
  template:
    metadata:
      labels:
        app.kubernetes.io/name: soju
    spec:
      containers:
        - name: soju
          image: soju
          env:
            - name: SOJU_INIT
              value: |
                user shane password1 admin
                user gowon password2

                server shane oragono irc+insecure://oragono:6667 shane
                server gowon oragono irc+insecure://oragono:6667 gowon

                channels shane oragono #test #test2 #test3
                channels gowon oragono #test #test2
          ports:
            - containerPort: 6667
              name: soju
          # volumeMounts:
          #   - name: initcfg
          #     mountPath: /config/init.cfg
          #     subPath: init.cfg
      # volumes:
      #   - name: initcfg
      #     configMap:
      #       name: initcfg
