---
apiVersion: v1
kind: Service
metadata:
  name: soju
spec:
  ports:
    - name: soju
      port: 6667
      targetPort: soju
  selector:
    app.kubernetes.io/name: soju
---
apiVersion: v1
kind: Service
metadata:
  name: soju2
spec:
  ports:
    - name: soju
      port: 6667
      targetPort: soju
  selector:
    app.kubernetes.io/name: soju
